num_modes : 4
manager:
  type: parallel
  preprocess_only: False

feature_extractors :
- resnet101
- resnet101
- resnet101
- resnet101

fusion:
  out_features: 1024

profiler:
  num_iterations: 10
  log_dir: log/synthetic
  name: parallel